// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADzC2x3ck11P9NcgU-xSvSIFT-IvkHKgs',
    appId: '1:318860834514:web:24b7a013c6bf40a8361f0b',
    messagingSenderId: '318860834514',
    projectId: 'card-upgo-run',
    authDomain: 'card-upgo-run.firebaseapp.com',
    storageBucket: 'card-upgo-run.appspot.com',
    measurementId: 'G-VCMFNC03E0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWzACQfpHDmbMETU9UoM2VnyW2D76X6Ck',
    appId: '1:318860834514:android:42eb0b2b59499bbb361f0b',
    messagingSenderId: '318860834514',
    projectId: 'card-upgo-run',
    storageBucket: 'card-upgo-run.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg80N9bdJN7-Olb9q0NS2O-96kDmK9ZfA',
    appId: '1:318860834514:ios:7a0151aee1576fcb361f0b',
    messagingSenderId: '318860834514',
    projectId: 'card-upgo-run',
    storageBucket: 'card-upgo-run.appspot.com',
    iosBundleId: 'com.example.cardUpgoRun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg80N9bdJN7-Olb9q0NS2O-96kDmK9ZfA',
    appId: '1:318860834514:ios:7a0151aee1576fcb361f0b',
    messagingSenderId: '318860834514',
    projectId: 'card-upgo-run',
    storageBucket: 'card-upgo-run.appspot.com',
    iosBundleId: 'com.example.cardUpgoRun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADzC2x3ck11P9NcgU-xSvSIFT-IvkHKgs',
    appId: '1:318860834514:web:a97cf3da77693019361f0b',
    messagingSenderId: '318860834514',
    projectId: 'card-upgo-run',
    authDomain: 'card-upgo-run.firebaseapp.com',
    storageBucket: 'card-upgo-run.appspot.com',
    measurementId: 'G-KM4LMKT9WP',
  );
}
